name: instagram_clean_arch
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  toast: ^0.3.0
  #state management
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_icons: ^1.1.0
  #Firebase
  cloud_firestore: ^3.5.0
  firebase_storage: ^10.3.10
  firebase_auth: ^3.11.0
  firebase_core: ^1.24.0
  #Service Locator
  get_it: ^7.2.0
  flutter_svg: ^1.1.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  uuid: ^3.0.6
  cached_network_image: ^3.2.1
  #show toast
  fluttertoast: ^8.0.9
  modal_bottom_sheet: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/.

